version: '3'

services:
  frontend:
    environment:
      PRODUCTION_PORT: 3001
      PRODUCTION_DB: mongodb://database/calculator
    build: .
    depends_on:
      - 'database'
    ports:
      - '3001:3001'

  database:
    image: mongo:latest